apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: my-database
      example: crud-vertx
      app.kubernetes.io/part-of: crud-example
      app.kubernetes.io/name: crud-db
      app.kubernetes.io/component: database
      app.openshift.io/runtime: postgresql
      app.openshift.io/runtime-version: "10"
    name: my-database
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhscl/postgresql-10-rhel7
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhscl/postgresql-10-rhel7
      name: latest

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: my-database
      example: crud-vertx
      app.kubernetes.io/part-of: crud-example
      app.kubernetes.io/name: crud-db
      app.kubernetes.io/component: database
      app.openshift.io/runtime: postgresql
      app.openshift.io/runtime-version: "10"
    name: my-database
  spec:
    replicas: 1
    selector:
      app: my-database
      example: crud-vertx
      deploymentconfig: my-database
    template:
      metadata:
        labels:
          app: my-database
          example: crud-vertx
          deploymentconfig: my-database
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            value: my_data
          - name: POSTGRESQL_PASSWORD
            value: secret
          - name: POSTGRESQL_USER
            value: luke
          image: registry.access.redhat.com/rhscl/postgresql-10-rhel7
          name: my-database
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: my-database-volume-1
        volumes:
        - emptyDir: {}
          name: my-database-volume-1
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - my-database
        from:
          kind: ImageStreamTag
          name: my-database:latest
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: my-database
      example: crud-vertx
      app.kubernetes.io/part-of: crud-example
      app.kubernetes.io/name: crud-db
      app.kubernetes.io/component: database
      app.openshift.io/runtime: postgresql
      app.openshift.io/runtime-version: "10"
    name: my-database
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: my-database
      example: crud-vertx
      deploymentconfig: my-database
kind: List
metadata: {}
